const { Prisma } = require('@prisma/client');

const players = [{
	"firstname":"Eden",
	"lastName":"Hazard",
	"goal":93,
	"salary":118000000,
	"device":"$",
	"pictureURl":""},
{
	"firstname":"Gareth",
	"lastName":"Bale",
	"goal":39,
	"salary":31200000,
	"device":"£",
	"pictureURl":""},
{
	"firstname":"Paul",
	"lastName":"Pogba",
	"goal":69,
	"salary":34000000,
	"device":"€",
	"pictureURl":""},
{
	"firstname":"Andres",
	"lastName":"Iniesta",
	"goal":126,
	"salary":35000000,
	"device":"$",
	"pictureURl":""},
{
	"firstname":"Robert ",
	"lastName":"Lewandowski",
	"goal":134,
	"salary":23000000,
	"device":"€",
	"pictureURl":""},
{
	"firstname":"Mohamed",
	"lastName":"Salah",
	"goal":97,
	"salary":19730000,
	"device":"€",
	"pictureURl":""},
{
	"firstname":"Kylian",
	"lastName":"Mbappé",
	"goal":125,
	"salary":22000000,
	"device":"€",
	"pictureURl":""},
{
	"firstname":"Neymar",
	"lastName":"JR.",
	"goal":33,
	"salary":95000000,
	"device":"€",
	"pictureURl":""},
{
	"firstname":"Lionel",
	"lastName":"Messi",
	"goal":299,
	"salary":110000000,
	"device":"$",
	"pictureURl":""},
{
	"firstname":"Cristiano",
	"lastName":"Ronaldo",
	"goal":298,
	"salary":125000000,
	"device":"£",
	"pictureURl":""},
{
	"firstname":"Marcos Aoás Corrêa",
	"lastName":"Marquinhos",
	"goal":44,
	"salary":1200000,
	"device":"€",
	"pictureURl":""},
{
	"firstname":"Marco",
	"lastName":"Verratti",
	"goal":30,
	"salary":599999,
	"device":"€",
	"pictureURl":""},
{
	"firstname":"karim",
	"lastName":"Benzema",
	"goal":99,
	"salary":5000999,
	"device":"€",
	"pictureURl":""},
{
	"firstname":"Michel",
	"lastName":"Platini",
	"goal":96,
	"salary":45,
	"device":"Fr",
	"pictureURl":""},
{
	"firstname":"Hakim ",
	"lastName":"Ziyech",
	"goal":399,
	"salary":15000000,
	"device":"MAD",
	"pictureURl":""},
{
	"firstname":"Romain",
	"lastName":"Saïss",
	"goal":19,
	"salary":45000000,
	"device":"MAD",
	"pictureURl":""},
{
	"firstname":"Sofiane",
	"lastName":"Boufal",
	"goal":45,
	"salary":35000000,
	"device":"MAD",
	"pictureURl":""},
{
	"firstname":"Edson Arantes do Nascimento",
	"lastName":"Pelé",
	"goal":196,
	"salary":400000,
	"device":"$",
	"pictureURl":""},
{
	"firstname":"Diego",
	"lastName":"Maradona",
	"goal":450,
	"salary":500000,
	"device":"$",
	"pictureURl":""},
{
	"firstname":"",
	"lastName":"",
	"goal":0,
	"salary":0,
	"device":"€",
	"pictureURl":""},

]



module.exports = {
  players
};
