import './globals.css';
import React from 'react';
import { Roboto } from 'next/font/google';
import props from '../interfaces/props';
import Navbar from './components/Navbar/Navbar';
export const metadata = {
  title: 'Hackatlon Solution',
  description: 'Generated by Ismail Bayoussef',
};
const roboto = Roboto({
  subsets: ['latin'],
  weight: '400',
});
const RootLayout: React.FC<props.ContainerProps> = ({ children }) => {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
